- name: copy config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/folder.xml
#  loop:
#    - src: job.xml
#      dest: /tmp/job.xml
#    - src: folder.xml
#      dest: /tmp/folder.xml

- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{item}}"
    password: admin123
    url: http://172.31.19.57:8080
    user: admin