- name: copy config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/job.xml') }}"
    name: "{{item}}"
    password: admin123
    url: http://localhost:8080
    user: admin
  loop:
    - frontend
    - catalogue
    - cart
